services:
  - type: web
    name: crypto
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crypto.wsgi"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
databases:
  - name: crypto-db

jobs:
  - type: worker
    name: migrate
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate"
