# Generated by Django 5.2.1 on 2025-07-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0009_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='account_name',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(default='Not Provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_name',
            field=models.CharField(default='Not Provided', max_length=255),
            preserve_default=False,
        ),
    ]
