# Generated by Django 5.2.1 on 2025-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0010_withdraw_account_name_withdraw_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
