# Generated by Django 5.2.1 on 2025-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0011_alter_withdraw_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
