# Generated by Django 5.2.1 on 2025-08-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0013_withdrawal_delete_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
