# Generated by Django 5.2.1 on 2025-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitcoin', '0014_alter_withdrawal_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
